language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - openjdk-8-jre-headless

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - export TRAVIS_BUILD_DIR="/home/travis/build/talis/aspire-moodle-integration/moodle-activity-module-lti-wrapper/mod/aspirelists"
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci grunt
  - moodle-plugin-ci savepoints # check plugin upgrade steps
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  #- moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  #- moodle-plugin-ci behat 
